import { Color } from "@raycast/api"

export const typeColors: { [key: string]: Color.Raw } = {
    "Effect Monster": Color.Orange,
    "Flip Effect Monster": Color.Orange,
    "Fusion Monster": Color.Purple,
    "Gemini Monster": Color.Orange,
    "Link Monster": Color.Blue,
    "Normal Monster": Color.Yellow,
    "Normal Tuner Monster": Color.Yellow,
    "Pendulum Effect Fusion Monster": Color.Red,
    "Pendulum Effect Monster": Color.Red,
    "Pendulum Effect Ritual Monster": Color.Red,
    "Pendulum Flip Effect Monster": Color.Red,
    "Pendulum Normal Monster": Color.Red,
    "Pendulum Tuner Effect Monster": Color.Red,
    "Ritual Effect Monster": Color.Blue,
    "Ritual Monster": Color.Blue,
    "Skill Card": Color.Blue,
    "Spell Card": Color.Green,
    "Synchro Monster": "DFDBDA",
    "Synchro Pendulum Effect Monster": Color.Red,
    "Synchro Tuner Monster": "DFDBDA",
    "Toon Monster": Color.Orange,
    "Token": "7E7A79",
    "Trap Card": Color.Magenta,
    "Tuner Monster": Color.Orange,
    "Union Effect Monster": Color.Orange,
    "XYZ Monster": "0D0D0D",
    "XYZ Pendulum Effect Monster": Color.Red
  };